
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 14 09:30:32 ART 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMIENZO = 11;
  public static final int MENOS = 4;
  public static final int ESTRING = 20;
  public static final int MENOR = 7;
  public static final int IGUAL = 2;
  public static final int LETRA = 19;
  public static final int THEN = 16;
  public static final int PARC = 10;
  public static final int IF = 15;
  public static final int ENTER = 17;
  public static final int PARA = 9;
  public static final int POR = 5;
  public static final int MAYOR = 8;
  public static final int EOF = 0;
  public static final int DIGITO = 18;
  public static final int SALIDA = 13;
  public static final int DIV = 6;
  public static final int error = 1;
  public static final int ENTRADA = 14;
  public static final int FIN = 12;
  public static final int MAS = 3;
}

